name: Backend CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/HotelBookingApplication

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t hotel-backend .